# Generated by Django 4.0.4 on 2022-04-28 19:59

from django.db import migrations, models
import django.db.models.deletion
import webapi.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GivenIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeSlot', models.PositiveSmallIntegerField(validators=[webapi.models.validate_time_slot])),
            ],
            options={
                'db_table': 'given_in',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Graded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField()),
            ],
            options={
                'db_table': 'graded',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prereq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'prereq',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('classroomId', models.IntegerField(primary_key=True, serialize=False)),
                ('campus', models.CharField(max_length=255)),
                ('capacity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DatabaseManager',
            fields=[
                ('username', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departmentId', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('username', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('courses', models.TextField()),
                ('studentId', models.IntegerField(unique=True)),
                ('gpa', models.FloatField()),
                ('completedCredits', models.PositiveSmallIntegerField()),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapi.department')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('username', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=25, validators=[webapi.models.validate_instructor_title])),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapi.department')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('courseId', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('credits', models.PositiveSmallIntegerField()),
                ('quota', models.PositiveIntegerField()),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapi.instructor')),
            ],
        ),
    ]
